#! /bin/sh

######################################################
#######################START##########################
######################################################

dex --autostart --environment bspwm &
polybar &
picom --config ~/.config/picom/picom.conf &
dunst &
feh --bg-fill ~/Pictures/wallpapers/dendra.jpg &
pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
blueman-applet &
(sleep 3 && discord) &
(sleep 2 && flameshot) &

######################################################
#######################BSPWM##########################
######################################################
BSPDIR="$HOME/.config/bspwm"
export PATH="${PATH}:$HOME/.config/bspwm/bin"
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=xcb
export ELECTRON_ENABLE_LOGGING=true
export ELECTRON_USE_ZGC=1
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export GTK_CSD=0
export GTK_THEME="catppuccin-macchiato-blue-standard+default"


## Bspwm appearance
CURRENT_BORDER='2'
CURRENT_GAP='5'
CURRENT_SRATIO='0.50'

## Manager Workspaces
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '󰨞' '' '' '' '' '󰓓'
		let name++
	done
}
workspaces

## Apply bspwm configurations
bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"
bspc config focused_border_color  "#7287fd"
bspc config normal_border_color  "#7c7f93"
bspc config active_border_color "#dd7878"
bspc config presel_feedback_color  "#89B8F7"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a gnome-calculator state=floating
bspc rule -a Brave-browser desktop='^2' follow=on focus=on
bspc rule -a Steam desktop='^6' follow=on focus=on
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a discord desktop='^4' follow=on focus=on
bspc rule -a 'github-desktop' desktop='^3' follow=on focus=on
bspc rule -a github-desktop desktop='^3' follow=on focus=on
bspc rule -a thunderbird desktop='^2' follow=on focus=on
bspc rule -a 'VirtualBox Manager' desktop='^0' follow=on focus=on
bspc rule -a GParted desktop='^0' follow=on focus=on

declare -a files=("Github Desktop" ranger Thunar)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

declare -a code=(nvim cursor code)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

declare -a settings=(Lxappearance qemu kvm )
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^0' state=floating follow=on focus=on; done



xrandr --output DP-1 --mode 2560x1440 --rate 144.00 --set TearFree on

